# SwiftLint Configuration for SIROS SDK

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - unowned_variable_capture

excluded:
  - .build
  - Package.swift

force_cast: warning
force_try: warning

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - iv
    - ks
