// Copyright 2026 SIROS Foundation. BSD 2-Clause License.

import Foundation

// NOTE: This file requires the SirosWscdFFI binary dependency (XCFramework)
// generated by `make xcframework` in the siros-wscd-manager crate.
// Until the XCFramework is published, this file compiles conditionally.

#if canImport(SirosWscdFFI)
import SirosWscdFFI

/// Provides user authentication credentials when requested by the WSCD.
///
/// Implement this protocol in the wallet application to handle
/// PIN entry prompts and WebAuthn assertion ceremonies during
/// signing operations that require 2FA (e.g. R2PS remote signing).
///
/// Note: These methods are called synchronously from the FFI queue.
/// Implementations that show UI should use platform mechanisms to
/// block until the user completes the interaction.
public protocol AuthProvider: AnyObject, Sendable {
    /// Request the user's PIN (e.g. for OPAQUE authentication).
    /// - Returns: The PIN as raw bytes (UTF-8 encoded).
    /// - Throws: If the user cancels.
    func requestPin() throws -> Data

    /// Request a WebAuthn assertion.
    /// - Parameters:
    ///   - challenge: The authentication challenge bytes.
    ///   - rpId: The Relying Party ID.
    ///   - allowedCredentials: List of allowed credential IDs.
    /// - Returns: The CBOR-encoded authenticator assertion response.
    /// - Throws: If the user cancels or no credential is available.
    func requestWebauthnAssertion(
        challenge: Data,
        rpId: String,
        allowedCredentials: [Data]
    ) throws -> Data
}

/// `UniFFISigner` wraps the Rust `siros-wscd-manager` UniFFI bindings
/// into the SDK's `Signer` protocol.
///
/// This enables the native SDK to use any WSCD plugin (softkey, R2PS,
/// FIDO2) through the same interface used by the software `JweKeystore`.
///
/// Usage:
/// ```swift
/// let config = FfiWscdConfig(defaultPlugin: "softkey")
/// let signer = try UniFFISigner(config: config)
/// let keystore = WscdKeystoreAdapter(signer: signer)
/// ```
public final class UniFFISigner: Signer, @unchecked Sendable {

    let ffi: FfiWscdManager
    private weak var authProvider: AuthProvider?
    /// Serial queue for ordered access to FFI bindings.
    private let ffiQueue = DispatchQueue(label: "org.sirosfoundation.UniFFISigner.ffi")
    /// Cache of key ID → JWK JSON Data, populated at generateKey time.
    private var publicKeyCache: [String: Data] = [:]
    private let cacheLock = NSLock()

    /// Create a UniFFI-backed signer.
    ///
    /// - Parameters:
    ///   - config: WSCD manager configuration.
    ///   - authProvider: Optional callback for user authentication (PIN/WebAuthn).
    public init(config: FfiWscdConfig, authProvider: AuthProvider? = nil) throws {
        self.ffi = FfiWscdManager(config: config)
        self.authProvider = authProvider
        try self.ffi.registerSoftkeyPlugin()
    }

    /// Register the R2PS remote HSM plugin.
    ///
    /// - Parameters:
    ///   - config: R2PS server connection parameters.
    ///   - transport: HTTP transport for R2PS protocol messages.
    ///   - pake: OPAQUE (RFC 9807) client for PAKE authentication.
    public func registerR2psPlugin(
        config: FfiR2psConfig,
        transport: FfiHttpTransport,
        pake: FfiPakeClient
    ) throws {
        try ffi.registerR2psPlugin(config: config, transport: transport, pake: pake)
    }

    // MARK: - Signer conformance

    public func generateKey(algorithm: String) async throws -> String {
        try await onFFIQueue {
            let ffiAlgorithm = try Self.mapAlgorithm(algorithm)
            let result = try self.ffi.generateKey(
                algorithm: ffiAlgorithm,
                auth: self.authCallbackBridge(),
                progress: NoOpProgressCallback()
            )
            self.cacheLock.lock()
            self.publicKeyCache[result.kid] = Data(result.publicKeyJwk.utf8)
            self.cacheLock.unlock()
            return result.kid
        }
    }

    public func sign(keyId: String, data: Data) async throws -> Data {
        try await onFFIQueue {
            let result = try self.ffi.sign(
                kid: keyId,
                data: data,
                algorithm: .es256, // algorithm is inferred from key by the manager
                auth: self.authCallbackBridge(),
                progress: NoOpProgressCallback()
            )
            return result.data
        }
    }

    public func listKeys() async throws -> [SignerKeyInfo] {
        try await onFFIQueue {
            try self.ffi.listKeys().map {
                SignerKeyInfo(keyId: $0.kid, algorithm: Self.algorithmToString($0.algorithm))
            }
        }
    }

    public func deleteKey(keyId: String) async throws {
        try await onFFIQueue {
            try self.ffi.deleteKey(kid: keyId)
            self.cacheLock.lock()
            self.publicKeyCache.removeValue(forKey: keyId)
            self.cacheLock.unlock()
        }
    }

    public func attestationChain(keyId: String) async throws -> [Data]? {
        try await onFFIQueue {
            try self.ffi.attestationChain(kid: keyId)?.certificates
        }
    }

    public func exportPublicKey(keyId: String) async throws -> Data {
        try await onFFIQueue {
            self.cacheLock.lock()
            let cached = self.publicKeyCache[keyId]
            self.cacheLock.unlock()
            guard let jwkData = cached else {
                throw UniFFISignerError.publicKeyNotCached(keyId: keyId)
            }
            return jwkData
        }
    }

    public func migrateKey(keyId: String, targetPlugin: String) async throws -> MigrationResult {
        try await onFFIQueue {
            let result = try self.ffi.migrateKey(
                kid: keyId,
                targetPluginId: targetPlugin,
                auth: self.authCallbackBridge()
            )
            switch result {
            case .migrated(let newKid):
                return .migrated(newKeyId: newKid)
            case .reEnrollmentRequired(let oldKid):
                return .reEnrollmentRequired(oldKeyId: oldKid)
            }
        }
    }

    public func securityProperties(keyId: String) async throws -> SignerSecurityProperties {
        try await onFFIQueue {
            let props = try self.ffi.securityProperties(kid: keyId)
            return SignerSecurityProperties(
                keyStorage: [Self.keyStorageToString(props.keyStorage)],
                userAuthentication: props.userAuthentication,
                certification: Self.certificationToSdk(props.certification),
                amr: props.amr
            )
        }
    }

    /// Export the softkey plugin container as JSON bytes for encrypted backup.
    public func exportSoftkeyContainer() throws -> Data {
        Data(try ffi.exportSoftkeyContainer())
    }

    /// Import a softkey container (JSON bytes) to restore keys from backup.
    public func importSoftkeyContainer(_ container: Data) throws {
        try ffi.importSoftkeyContainer(container: [UInt8](container))
    }

    // MARK: - Private helpers

    /// Execute a blocking FFI call on the serial FFI queue.
    func onFFIQueue<T>(_ block: @escaping () throws -> T) async throws -> T {
        try await withCheckedThrowingContinuation { continuation in
            ffiQueue.async {
                do {
                    let result = try block()
                    continuation.resume(returning: result)
                } catch {
                    continuation.resume(throwing: error)
                }
            }
        }
    }

    func authCallbackBridge() -> AuthCallbackBridge {
        AuthCallbackBridge(provider: authProvider)
    }

    // MARK: - Type mapping

    private static func mapAlgorithm(_ s: String) throws -> FfiAlgorithm {
        switch s.uppercased() {
        case "ES256": return .es256
        case "EDDSA", "ED25519": return .edDsa
        default: throw UniFFISignerError.unsupportedAlgorithm(s)
        }
    }

    private static func algorithmToString(_ alg: FfiAlgorithm) -> String {
        switch alg {
        case .es256: return "ES256"
        case .edDsa: return "EdDSA"
        }
    }

    private static func keyStorageToString(_ ks: FfiKeyStorageType) -> String {
        switch ks {
        case .software: return "software"
        case .hardware: return "hardware"
        case .remoteHsm: return "remote_hsm"
        case .trustedExecution: return "trusted_execution"
        }
    }

    private static func certificationToSdk(_ cert: FfiCertificationLevel) -> CertificationInfo {
        switch cert {
        case .none: return .none
        case .baseline: return .certified(scheme: "EUCC", assuranceLevel: "baseline")
        case .substantial: return .certified(scheme: "EUCC", assuranceLevel: "substantial")
        case .high: return .certified(scheme: "EUCC", assuranceLevel: "high")
        }
    }
}

// MARK: - Errors

public enum UniFFISignerError: Error, LocalizedError {
    case unsupportedAlgorithm(String)
    case publicKeyNotCached(keyId: String)

    public var errorDescription: String? {
        switch self {
        case .unsupportedAlgorithm(let alg):
            return "Unsupported algorithm: \(alg)"
        case .publicKeyNotCached(let kid):
            return "Public key not cached for \(kid). Key was generated before this session or on another device."
        }
    }
}

// MARK: - Auth callback bridge

final class AuthCallbackBridge: FfiAuthCallback, @unchecked Sendable {
    private weak var provider: AuthProvider?

    init(provider: AuthProvider?) {
        self.provider = provider
    }

    func requestPin() throws -> Data {
        guard let provider = provider else {
            throw FfiWscdError.AuthCancelled(message: "No AuthProvider configured")
        }
        return try provider.requestPin()
    }

    func requestWebauthnAssertion(
        challenge: Data,
        rpId: String,
        allowedCredentials: [Data]
    ) throws -> Data {
        guard let provider = provider else {
            throw FfiWscdError.AuthCancelled(message: "No AuthProvider configured")
        }
        return try provider.requestWebauthnAssertion(
            challenge: challenge,
            rpId: rpId,
            allowedCredentials: allowedCredentials
        )
    }
}

// MARK: - No-op progress callback

final class NoOpProgressCallback: FfiProgressCallback, @unchecked Sendable {
    func onProgress(progress: FfiOperationProgress) { /* no-op */ }
}

// MARK: - CTAP2 bridge

/// Bridges the SDK's `Ctap2TransportProvider` to the UniFFI `FfiCtap2Transport` callback.
///
/// The FFI expects structured CTAP2 operations (makeCredential, getAssertion)
/// while the SDK provider exposes a raw command-level interface. This bridge
/// constructs the appropriate CBOR commands and parses responses.
///
/// Note: CTAP2/FIDO2 plugin support is not yet wired — the R2PS plugin
/// uses its own HTTP transport and does not require CTAP2.
private final class Ctap2TransportBridge: FfiCtap2Transport, @unchecked Sendable {
    private let provider: Ctap2TransportProvider

    init(_ provider: Ctap2TransportProvider) {
        self.provider = provider
    }

    func ctap2MakeCredential(
        clientDataHash: [UInt8],
        rpId: String,
        userId: [UInt8],
        algorithms: [Int64]
    ) throws -> [UInt8] {
        // CTAP2 makeCredential requires CBOR command construction.
        // This will be implemented when the FIDO2 plugin is activated.
        throw NSError(
            domain: "UniFFISigner.Ctap2",
            code: -1,
            userInfo: [NSLocalizedDescriptionKey: "CTAP2 makeCredential not yet implemented"]
        )
    }

    func ctap2GetAssertion(
        rpId: String,
        challenge: [UInt8],
        credentialHandles: [[UInt8]],
        dataToSign: [[UInt8]]
    ) throws -> [[UInt8]] {
        // CTAP2 getAssertion requires CBOR command construction.
        // This will be implemented when the FIDO2 plugin is activated.
        throw NSError(
            domain: "UniFFISigner.Ctap2",
            code: -1,
            userInfo: [NSLocalizedDescriptionKey: "CTAP2 getAssertion not yet implemented"]
        )
    }
}

#endif // canImport(SirosWscdFFI)
