// Copyright 2026 SIROS Foundation. BSD 2-Clause License.

import Foundation

// NOTE: This file requires the SirosWscdFFI binary dependency (XCFramework)
// generated by `make xcframework` in the siros-wscd-manager crate.
// Until the XCFramework is published, this file compiles conditionally.

#if canImport(SirosWscdFFI)
import SirosWscdFFI

/// `UniFFISigner` wraps the Rust `siros-wscd-manager` UniFFI bindings
/// into the SDK's `Signer` protocol.
///
/// This enables the native SDK to use any WSCD plugin (softkey, R2PS,
/// FIDO2) through the same interface used by the software `JweKeystore`.
///
/// Usage:
/// ```swift
/// let config = FfiWscdConfig(
///     defaultPlugin: "softkey",
///     pluginConfigs: [:]
/// )
/// let signer = try UniFFISigner(config: config)
/// let keystore = WscdKeystoreAdapter(signer: signer)
/// let wallet = SirosWallet(keystore: keystore)
/// ```
public final class UniFFISigner: Signer, @unchecked Sendable {

    private let ffi: FfiWscdManager
    private let ctap2Bridge: Ctap2TransportBridge?
    /// Serial queue for ordered access to FFI bindings.
    private let ffiQueue = DispatchQueue(label: "org.sirosfoundation.UniFFISigner.ffi")

    /// Create a UniFFI-backed signer.
    ///
    /// - Parameters:
    ///   - config: WSCD manager configuration (default plugin, plugin configs).
    ///   - transport: Optional CTAP2 transport provider for FIDO2 plugin.
    public init(config: FfiWscdConfig, transport: Ctap2TransportProvider? = nil) throws {
        self.ctap2Bridge = transport.map { Ctap2TransportBridge($0) }
        self.ffi = try FfiWscdManager(
            config: config,
            transport: ctap2Bridge
        )
    }

    // MARK: - Signer conformance

    public func generateKey(algorithm: String) async throws -> String {
        try await onFFIQueue {
            try self.ffi.generateKey(algorithm: algorithm)
        }
    }

    public func sign(keyId: String, data: Data) async throws -> Data {
        try await onFFIQueue {
            let result = try self.ffi.sign(kid: keyId, data: [UInt8](data), callback: nil)
            return Data(result.signature)
        }
    }

    public func listKeys() async throws -> [SignerKeyInfo] {
        try await onFFIQueue {
            try self.ffi.listKeys().map {
                SignerKeyInfo(keyId: $0.kid, algorithm: $0.algorithm)
            }
        }
    }

    public func deleteKey(keyId: String) async throws {
        try await onFFIQueue {
            try self.ffi.deleteKey(kid: keyId)
        }
    }

    public func attestationChain(keyId: String) async throws -> [Data]? {
        try await onFFIQueue {
            try self.ffi.attestationChain(kid: keyId)?.map { Data($0) }
        }
    }

    public func exportPublicKey(keyId: String) async throws -> Data {
        try await onFFIQueue {
            let jwk = try self.ffi.exportPublicKey(kid: keyId)
            return Data(jwk)
        }
    }

    public func migrateKey(keyId: String, targetPlugin: String) async throws -> MigrationResult {
        try await onFFIQueue {
            let result = try self.ffi.migrateKey(kid: keyId, targetPlugin: targetPlugin)
            switch result {
            case .migrated(let newKid):
                return .migrated(newKeyId: newKid)
            case .reEnrollmentRequired(let oldKid):
                return .reEnrollmentRequired(oldKeyId: oldKid)
            }
        }
    }

    public func securityProperties(keyId: String) async throws -> SignerSecurityProperties {
        try await onFFIQueue {
            let props = try self.ffi.securityProperties(kid: keyId)
            return SignerSecurityProperties(
                keyStorage: props.keyStorage,  // [String] from FFI
                userAuthentication: props.userAuthentication,
                certification: .none,  // TODO: map structured certification from FFI
                amr: props.amr
            )
        }
    }

    // MARK: - Private helpers

    /// Execute a blocking FFI call on the serial FFI queue.
    private func onFFIQueue<T>(_ block: @escaping () throws -> T) async throws -> T {
        try await withCheckedThrowingContinuation { continuation in
            ffiQueue.async {
                do {
                    let result = try block()
                    continuation.resume(returning: result)
                } catch {
                    continuation.resume(throwing: error)
                }
            }
        }
    }
}

// MARK: - CTAP2 bridge

/// Bridges the SDK's `Ctap2TransportProvider` to the UniFFI `FfiCtap2Transport` callback.
private final class Ctap2TransportBridge: FfiCtap2Transport, @unchecked Sendable {
    private let provider: Ctap2TransportProvider

    init(_ provider: Ctap2TransportProvider) {
        self.provider = provider
    }

    func send(command: [UInt8]) throws -> [UInt8] {
        let semaphore = DispatchSemaphore(value: 0)
        // Use a class-based box to safely coordinate deallocation with the async task.
        final class Box: @unchecked Sendable {
            var result: Result<[UInt8], Error>?
            var consumed = false
            let lock = NSLock()
        }
        let box = Box()
        Task.detached { [provider, box] in
            do {
                let response = try await provider.send(command: Data(command))
                box.lock.lock()
                if !box.consumed {
                    box.result = .success([UInt8](response))
                }
                box.lock.unlock()
            } catch {
                box.lock.lock()
                if !box.consumed {
                    box.result = .failure(error)
                }
                box.lock.unlock()
            }
            semaphore.signal()
        }
        _ = semaphore.wait(timeout: .now() + 30)
        box.lock.lock()
        let r = box.result
        box.consumed = true
        box.lock.unlock()
        guard let result = r else {
            throw NSError(domain: "UniFFISigner", code: -1, userInfo: [NSLocalizedDescriptionKey: "CTAP2 send timed out"])
        }
        return try result.get()
    }

    func isAvailable() -> Bool {
        let semaphore = DispatchSemaphore(value: 0)
        final class Box: @unchecked Sendable {
            var result = false
            var consumed = false
            let lock = NSLock()
        }
        let box = Box()
        Task.detached { [provider, box] in
            let available = await provider.isAvailable()
            box.lock.lock()
            if !box.consumed {
                box.result = available
            }
            box.lock.unlock()
            semaphore.signal()
        }
        _ = semaphore.wait(timeout: .now() + 5)
        box.lock.lock()
        let result = box.result
        box.consumed = true
        box.lock.unlock()
        return result
    }
}

// MARK: - FFI enum mapping

// FFI bridge types will need updating when siros-wscd-manager exposes
// the new [String] key_storage and structured certification.
// For now, the UniFFISigner maps to the new types directly.

#endif // canImport(SirosWscdFFI)
