// Copyright 2026 SIROS Foundation. BSD 2-Clause License.

// The native zk_cred_bbs XCFramework only ships iOS slices - see
// BbsProofSystem.swift's own `#if os(iOS)` gating. On any other platform
// this file is empty, which is why a Linux `swift test` proves nothing
// about it.
#if os(iOS)

import Foundation
import XCTest
@testable import SirosCredentials

/// `BbsProofSystem` against a real credential.
///
/// Mirrors Kotlin's `BbsProofSystemTest`, which runs the same fixture
/// through the same calls on a real Pixel. Keeping the two in step is the
/// point: the two SDKs have diverged before in ways only a side-by-side
/// test caught.
///
/// The fixture is generated by the crate (`make sdk-fixture`). It proves
/// nothing about whether the BBS is correct - the crate's own
/// `tests/vectors.rs` answers that differentially against Emil Lundberg's
/// TypeScript - only that a credential survives the trip through this type.
///
/// Its `plain` case has no key binding, which is what lets the whole
/// present-and-verify path run here with no authenticator. The `keybind`
/// case needs a Schnorr-over-BLS12-381 signature that no Apple key store
/// can produce, so what is checked there is what this type asks the
/// authenticator FOR.
final class BbsProofSystemTests: XCTestCase {

    // MARK: - Fixture

    private struct Fixture {
        let issuedJwp: String
        let issuerPk: [UInt8]
        let committedMessages: [[UInt8]]
        let keybindPublicKeys: [[UInt8]]
        let secretProverBlind: [UInt8]
        let vct: String
    }

    private func fixture(_ name: String) throws -> Fixture {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "bbs_jwp_fixture", withExtension: "json"),
            "bbs_jwp_fixture.json missing from test resources"
        )
        let root = try JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any]
        let cases = try XCTUnwrap(root?["cases"] as? [String: Any])
        let c = try XCTUnwrap(cases[name] as? [String: Any])
        return Fixture(
            issuedJwp: try XCTUnwrap(c["issued_jwp"] as? String),
            issuerPk: Self.unhex(try XCTUnwrap(c["issuer_pk"] as? String)),
            committedMessages: (c["committed_messages"] as? [String] ?? []).map(Self.unhex),
            keybindPublicKeys: (c["keybind_public_keys"] as? [String] ?? []).map(Self.unhex),
            secretProverBlind: Self.unhex(try XCTUnwrap(c["secret_prover_blind"] as? String)),
            vct: try XCTUnwrap(c["vct"] as? String)
        )
    }

    private static func unhex(_ s: String) -> [UInt8] {
        var out = [UInt8]()
        out.reserveCapacity(s.count / 2)
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            out.append(UInt8(s[i..<j], radix: 16)!)
            i = j
        }
        return out
    }

    private func system(_ f: Fixture, _ suite: BbsSuiteId) -> BbsProofSystem {
        let state = BbsHolderState(
            issuerPublicKey: f.issuerPk,
            secretProverBlind: f.secretProverBlind,
            committedMessages: f.committedMessages,
            keybindPublicKeys: f.keybindPublicKeys
        )
        return BbsProofSystem(
            holderState: { _ in state },
            supportedVcts: [f.vct],
            suiteId: suite
        )
    }

    private func spec(_ params: [String: String]) -> ZkSystemSpec {
        ZkSystemSpec(id: "test", system: BbsProofSystem.systemIdentifier, params: params)
    }

    /// Fails the test if it is ever called.
    private let refusingSigner: ZkWitnessSigner = { algorithm, _ in
        XCTFail("the authenticator was asked for a \(algorithm) signature, but this credential has no key binding")
        return []
    }

    private let transcript = Array("a session transcript".utf8)

    // MARK: - Tests

    /// The whole path, end to end: a stored credential becomes a
    /// presentation that verifies and reveals exactly what was asked for.
    func testACredentialPresentsAndVerifies() async throws {
        let f = try fixture("plain")
        let result = try await system(f, .plain).generateProof(
            spec: spec(["nonce": "verifier-nonce", "aud": "https://verifier.test"]),
            document: .jwp(f.issuedJwp),
            sessionTranscript: transcript,
            requestedClaims: ["/given_name", "/address/country"],
            verifierIdentity: nil,
            signer: refusingSigner,
            priorState: nil
        )

        let presented = String(bytes: result.proofBytes, encoding: .utf8)!
        XCTAssertEqual(presented.split(separator: ".", omittingEmptySubsequences: false).count, 4,
                       "a presented JWP has four parts")

        let verified = try jwpVerify(suiteId: .plain, presentedJwp: presented, issuerPublicKey: Data(f.issuerPk))
        XCTAssertEqual(verified.vct, f.vct)
        XCTAssertEqual(
            verified.disclosed.map { [$0.pointer, $0.valueJson] },
            [["/address/country", "\"SE\""], ["/given_name", "\"Alice\""]]
        )

        // BBS has a pseudonym construction but this does not implement it,
        // and saying so is the point of the enum - a system that quietly
        // returned nothing would be indistinguishable from one that failed.
        XCTAssertEqual(result.pseudonymOutcome, .notSupportedBySystem)
        XCTAssertNil(result.pseudonym)
        XCTAssertNil(result.nextState, "nothing is cached between presentations")
    }

    /// Nothing beyond the requested claims may appear.
    ///
    /// The wallet holds a credential with eight claims and hands over one.
    /// A disclosure that leaked the rest would still verify, so only this
    /// catches it.
    func testOnlyTheRequestedClaimsAreRevealed() async throws {
        let f = try fixture("plain")
        let result = try await system(f, .plain).generateProof(
            spec: spec(["nonce": "n", "aud": "https://verifier.test"]),
            document: .jwp(f.issuedJwp),
            sessionTranscript: transcript,
            requestedClaims: ["/birth_date"],
            verifierIdentity: nil,
            signer: refusingSigner,
            priorState: nil
        )
        let presented = String(bytes: result.proofBytes, encoding: .utf8)!
        let verified = try jwpVerify(suiteId: .plain, presentedJwp: presented, issuerPublicKey: Data(f.issuerPk))
        XCTAssertEqual(verified.disclosed.count, 1)
        XCTAssertEqual(verified.disclosed[0].pointer, "/birth_date")

        for secret in ["Alice", "Andersson", "Stockholm", "0f1e2d3c"] {
            let encoded = Data("\"\(secret)\"".utf8).base64EncodedString()
                .replacingOccurrences(of: "+", with: "-")
                .replacingOccurrences(of: "/", with: "_")
                .replacingOccurrences(of: "=", with: "")
            XCTAssertFalse(presented.contains(encoded), "the presentation must not contain \(secret)")
        }
    }

    /// Two presentations of one credential must differ.
    ///
    /// This is the unlinkability property the whole construction exists
    /// for. It is also the one that fails silently: presentations built
    /// from a fixed random source would all verify perfectly while making
    /// every holder trackable across verifiers.
    func testPresentationsAreUnlinkable() async throws {
        let f = try fixture("plain")
        let sys = system(f, .plain)
        func present() async throws -> String {
            let r = try await sys.generateProof(
                spec: spec(["nonce": "the-same-nonce", "aud": "https://verifier.test"]),
                document: .jwp(f.issuedJwp),
                sessionTranscript: transcript,
                requestedClaims: ["/given_name"],
                verifierIdentity: nil,
                signer: refusingSigner,
                priorState: nil
            )
            return String(bytes: r.proofBytes, encoding: .utf8)!
        }
        let first = try await present()
        let second = try await present()
        XCTAssertNotEqual(first, second,
                          "same credential, same nonce, same claims - the proofs must still differ")
        // Both must verify, so the difference is re-randomisation and not damage.
        for p in [first, second] {
            _ = try jwpVerify(suiteId: .plain, presentedJwp: p, issuerPublicKey: Data(f.issuerPk))
        }
    }

    /// A key bound credential asks the authenticator for exactly one
    /// signature per bound key, with the algorithm that key actually uses.
    ///
    /// No Apple key store can produce a Schnorr signature over BLS12-381
    /// G1, so the request itself is what is checked here. Getting the
    /// algorithm wrong is the failure this guards: a wallet that signed
    /// with ES256 instead would produce a presentation that fails
    /// verification with nothing pointing at the key.
    func testAKeyBoundCredentialAsksTheAuthenticatorCorrectly() async throws {
        struct NoSigner: Error {}
        let f = try fixture("keybind")
        let asked = AskedRecorder()

        do {
            _ = try await system(f, .schnorr).generateProof(
                spec: spec(["nonce": "n", "aud": "https://verifier.test"]),
                document: .jwp(f.issuedJwp),
                sessionTranscript: transcript,
                requestedClaims: ["/given_name"],
                verifierIdentity: nil,
                signer: { algorithm, data in
                    await asked.record(algorithm: algorithm, length: data.count)
                    throw NoSigner()
                },
                priorState: nil
            )
            XCTFail("a signer that cannot sign must not yield a presentation")
        } catch is NoSigner {
            // expected
        }

        let calls = await asked.calls
        XCTAssertEqual(calls.count, 1, "one signature per key binding key")
        XCTAssertEqual(calls[0].algorithm, coseAlgBls12381G1Schnorr)
        XCTAssertEqual(calls[0].length, 32, "the challenge is prehashed to 32 octets - PROFILE.md DELTA 3")
    }

    /// The verifier's audience is not optional, and the two ways of
    /// supplying it agree.
    func testTheAudienceComesFromTheSpecOrTheVerifierIdentity() async throws {
        let f = try fixture("plain")
        let sys = system(f, .plain)
        func present(_ s: ZkSystemSpec, _ v: VerifierIdentity?) async throws {
            _ = try await sys.generateProof(
                spec: s, document: .jwp(f.issuedJwp), sessionTranscript: transcript,
                requestedClaims: ["/given_name"], verifierIdentity: v,
                signer: refusingSigner, priorState: nil
            )
        }
        try await present(spec(["nonce": "n", "aud": "https://verifier.test"]), nil)
        try await present(spec(["nonce": "n"]), VerifierIdentity(clientId: "https://verifier.test"))

        do {
            try await present(spec(["nonce": "n"]), nil)
            XCTFail("a presentation with no audience must be refused")
        } catch BbsProofError.missingAudience {
            // expected
        }
    }

    /// Every way a caller can ask for something this credential cannot do
    /// must fail before the authenticator is touched - a user prompt that
    /// leads nowhere is worse than an error.
    func testImpossibleRequestsAreRefused() async throws {
        let f = try fixture("plain")
        let sys = system(f, .plain)
        let ok = spec(["nonce": "n", "aud": "https://verifier.test"])

        do {
            _ = try await sys.generateProof(
                spec: ok, document: .jwp(f.issuedJwp), sessionTranscript: transcript,
                requestedClaims: ["/shoe_size"], verifierIdentity: nil,
                signer: refusingSigner, priorState: nil
            )
            XCTFail("a claim the credential does not have")
        } catch let BbsProofError.unknownClaims(missing, _) {
            XCTAssertEqual(missing, ["/shoe_size"])
        }

        do {
            _ = try await sys.generateProof(
                spec: ok, document: .sdJwtVc([1, 2]), sessionTranscript: transcript,
                requestedClaims: ["/given_name"], verifierIdentity: nil,
                signer: refusingSigner, priorState: nil
            )
            XCTFail("a document that is not a JWP")
        } catch let BbsProofError.wrongDocumentFormat(got) {
            XCTAssertEqual(got, "sdJwtVc")
        }

        // Without the blinding factor from issuance the credential cannot
        // be presented at all, and saying so beats failing inside the
        // prover.
        let stateless = BbsProofSystem(holderState: { _ in nil }, supportedVcts: [f.vct], suiteId: .plain)
        do {
            _ = try await stateless.generateProof(
                spec: ok, document: .jwp(f.issuedJwp), sessionTranscript: transcript,
                requestedClaims: ["/given_name"], verifierIdentity: nil,
                signer: refusingSigner, priorState: nil
            )
            XCTFail("no holder state")
        } catch BbsProofError.missingHolderState {
            // expected
        }
    }

    /// The presentation is bound to the session transcript.
    ///
    /// Every other presentation path in this SDK binds it, and the JWP
    /// drafts have no parameter for one, so this profile adds `sth`.
    /// Without it a captured presentation could be replayed into a
    /// different session that happened to reuse the nonce.
    func testTheProofIsBoundToTheSessionTranscript() async throws {
        let f = try fixture("plain")
        let sys = system(f, .plain)
        func present(_ t: [UInt8]) async throws -> String {
            let r = try await sys.generateProof(
                spec: spec(["nonce": "identical-nonce", "aud": "https://verifier.test"]),
                document: .jwp(f.issuedJwp), sessionTranscript: t,
                requestedClaims: ["/given_name"], verifierIdentity: nil,
                signer: refusingSigner, priorState: nil
            )
            return String(bytes: r.proofBytes, encoding: .utf8)!
        }
        let a = try await present(Array("session one".utf8))
        let b = try await present(Array("session two".utf8))
        let headerOf = { (p: String) in String(p.split(separator: ".", omittingEmptySubsequences: false)[0]) }
        XCTAssertNotEqual(headerOf(a), headerOf(b),
                          "the same nonce in two sessions must not produce the same header")

        // Splicing one session's header onto the other's proof must not verify.
        var parts = a.split(separator: ".", omittingEmptySubsequences: false).map(String.init)
        parts[0] = headerOf(b)
        XCTAssertThrowsError(
            try jwpVerify(suiteId: .plain, presentedJwp: parts.joined(separator: "."), issuerPublicKey: Data(f.issuerPk)),
            "a presentation replayed against another session must not verify"
        )
    }

    // MARK: - Routing (no native calls)

    /// The format is part of the match, so a verifier asking for an mdoc
    /// with a colliding type string does not land here.
    func testACredentialTypeIsFormatPlusType() throws {
        let f = try fixture("plain")
        let sys = system(f, .plain)
        XCTAssertTrue(sys.supportedCredentialTypes.contains(CredentialTypeRef(format: .jwp, typeId: f.vct)))
        XCTAssertFalse(sys.supportedCredentialTypes.contains(CredentialTypeRef(format: .msoMdoc, typeId: f.vct)))
        XCTAssertFalse(sys.supportedCredentialTypes.contains(CredentialTypeRef(format: .sdJwtVc, typeId: f.vct)))
    }

    func testItMatchesOnlyItsOwnSystemIdentifier() throws {
        let f = try fixture("plain")
        let sys = system(f, .plain)
        XCTAssertNil(sys.matchingSpec([ZkSystemSpec(id: "l", system: "longfellow-libzk-v1_8_2_4307_2945")], numAttributes: 1))
        XCTAssertNil(sys.matchingSpec([], numAttributes: 1))
        XCTAssertEqual(
            sys.matchingSpec(
                [ZkSystemSpec(id: "v", system: "vega-v1"),
                 ZkSystemSpec(id: "b", system: BbsProofSystem.systemIdentifier)],
                numAttributes: 1
            )?.system,
            BbsProofSystem.systemIdentifier
        )
    }

    /// **The attribute count is deliberately ignored**, which is the
    /// opposite of what the protocol asks of a circuit-based system.
    ///
    /// That requirement exists because a circuit is compiled for a fixed
    /// attribute count, and proving against the wrong one yields a proof a
    /// verifier rejects during deserialization. BBS has no circuit: the
    /// generators are derived from the credential's own message count at
    /// proving time, and the disclosed subset is chosen per presentation.
    /// Filtering here would reject requests this system can satisfy.
    func testAnyAttributeCountMatches() throws {
        let f = try fixture("plain")
        let sys = system(f, .plain)
        let requested = [ZkSystemSpec(id: "b", system: BbsProofSystem.systemIdentifier)]
        for n in [0, 1, 2, 17, 512] {
            XCTAssertEqual(sys.matchingSpec(requested, numAttributes: n)?.system,
                           BbsProofSystem.systemIdentifier,
                           "attribute count \(n) must still match")
        }
    }

    /// The registry resolves through the same path a wallet would use, so
    /// this checks the two ends actually meet.
    func testTheRegistryResolvesAJwpRequestToThisSystem() throws {
        let f = try fixture("plain")
        let registry = ZkProofSystemRegistry(systems: [system(f, .plain)])
        let requested = [ZkSystemSpec(id: "b", system: BbsProofSystem.systemIdentifier)]

        let resolved = registry.resolve(
            credentialType: CredentialTypeRef(format: .jwp, typeId: f.vct),
            requestedSpecs: requested, numAttributes: 2
        )
        XCTAssertEqual(resolved?.0.systemId, BbsProofSystem.systemIdentifier)

        XCTAssertNil(registry.resolve(
            credentialType: CredentialTypeRef(format: .jwp, typeId: "https://other.test/x"),
            requestedSpecs: requested, numAttributes: 2), "a vct this wallet holds no BBS credential for")
        XCTAssertNil(registry.resolve(
            credentialType: CredentialTypeRef(format: .msoMdoc, typeId: f.vct),
            requestedSpecs: requested, numAttributes: 2), "the right type in the wrong format")
        XCTAssertNil(registry.resolve(
            credentialType: CredentialTypeRef(format: .jwp, typeId: f.vct),
            requestedSpecs: [ZkSystemSpec(id: "x", system: "something-else")],
            numAttributes: 2), "a system this wallet does not have")
    }

    func testTheJwpDocumentCaseRoundTrips() {
        let compact = "aGVhZGVy.cGF5bG9hZA.c2ln"
        let doc = CredentialDocument.jwp(compact)
        XCTAssertEqual(doc.jwpCompact, compact)
        XCTAssertEqual(doc.bytes, Array(compact.utf8))
        XCTAssertEqual(doc.formatName, "jwp")
        // An SD-JWT VC over the same bytes is a different thing, and asking
        // it for a JWP must not silently succeed.
        XCTAssertNil(CredentialDocument.sdJwtVc(Array(compact.utf8)).jwpCompact)
    }

    func testTheJwpFormatHasItsOwnIdentifier() {
        XCTAssertEqual(CredentialFormat.jwp.rawValue, "jwp")
    }
}

/// Records what the authenticator was asked for, across an async boundary.
private actor AskedRecorder {
    struct Call { let algorithm: Int64; let length: Int }
    private(set) var calls: [Call] = []
    func record(algorithm: Int64, length: Int) { calls.append(Call(algorithm: algorithm, length: length)) }
}

#endif
